import { StyleSheet } from "react-native";

import { colors, spacing } from "../theme";

export const landscapeTimelineStyles = StyleSheet.create({
  shell: {
    marginTop: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
    gap: spacing.sm,
    position: "relative",
  },
  header: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  title: {
    fontSize: 28,
    fontWeight: "900",
  },
  controls: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  controlButton: {
    minHeight: 42,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    alignItems: "center",
    justifyContent: "center",
  },
  controlLabel: {
    fontSize: 15,
    fontWeight: "800",
  },
  addButton: {
    minHeight: 46,
    borderRadius: 999,
    paddingHorizontal: spacing.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  addLabel: {
    color: colors.white,
    fontSize: 17,
    fontWeight: "900",
  },
  dropdownLayer: {
    position: "absolute",
    top: 54,
    right: spacing.md,
    alignItems: "flex-end",
    zIndex: 20,
  },
  dropdownMenu: { width: 210, borderRadius: 10, borderWidth: 1, overflow: "hidden" },
  dropdownItem: { minHeight: 44, justifyContent: "center", paddingHorizontal: spacing.md },
  dropdownItemLabel: { fontSize: 15, fontWeight: "900" },
  monthPickerMenu: { width: 430, maxWidth: "100%", borderRadius: 10, borderWidth: 1, padding: spacing.sm, gap: spacing.sm },
  monthPickerHeader: { minHeight: 40, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm },
  yearButton: { minHeight: 34, borderRadius: 8, borderWidth: 1, justifyContent: "center", paddingHorizontal: spacing.sm },
  yearButtonLabel: { fontSize: 13, fontWeight: "900" },
  yearLabel: { fontSize: 17, fontWeight: "900" },
  monthGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs },
  monthOption: { width: 96, minHeight: 38, borderRadius: 8, borderWidth: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: spacing.xs },
  monthOptionLabel: { fontSize: 13, fontWeight: "800" },
  board: {
    minHeight: 268,
    borderRadius: 10,
    borderWidth: 1,
    overflow: "hidden",
  },
  contentRow: {
    flexDirection: "row",
  },
  sidebar: {
    width: 390,
    borderRightWidth: 1,
  },
  sidebarHeader: {
    height: 74,
    flexDirection: "row",
    borderBottomWidth: 1,
  },
  sidebarHeaderCell: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  projectHeaderCell: {
    width: 150,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  subsystemHeaderCell: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  sidebarHeaderText: {
    fontSize: 17,
    fontWeight: "900",
  },
  sidebarBody: {
    flexDirection: "row",
  },
  projectColumn: {
    width: 150,
    borderRightWidth: 1,
  },
  subsystemColumn: {
    flex: 1,
  },
  projectGroupCell: {
    borderBottomWidth: 1,
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
    gap: 4,
  },
  projectGroupLabel: {
    fontSize: 17,
    fontWeight: "900",
  },
  projectGroupCount: {
    fontSize: 12,
    fontWeight: "800",
  },
  laneLabel: {
    height: 74,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    paddingHorizontal: spacing.sm,
    gap: spacing.xs,
  },
  subsystemDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  lanePrimary: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: "900",
  },
  laneCount: {
    width: 34,
    fontSize: 11,
    fontWeight: "800",
    textAlign: "right",
  },
  laneSecondary: {
    width: 78,
    fontSize: 11,
    fontWeight: "700",
    textAlign: "right",
  },
  chart: {
    position: "relative",
  },
  monthLabel: {
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 1,
  },
  monthText: {
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  dayHeaderRow: {
    height: 42,
    flexDirection: "row",
    borderBottomWidth: 1,
  },
  dayHeaderCell: {
    width: 56,
    alignItems: "center",
    justifyContent: "center",
    borderRightWidth: 1,
  },
  weekday: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },
  dayNumber: {
    marginTop: 3,
    fontSize: 13,
    fontWeight: "900",
  },
  lane: {
    height: 74,
    position: "relative",
    flexDirection: "row",
    borderBottomWidth: 1,
  },
  dayCell: {
    width: 56,
    borderRightWidth: 1,
  },
  calendarWeekHeader: { height: 42, flexDirection: "row", borderBottomWidth: 1 },
  calendarHeaderCell: { flex: 1, alignItems: "center", justifyContent: "center", borderRightWidth: 1 },
  calendarGrid: { flexDirection: "row", flexWrap: "wrap" },
  calendarDay: { width: "14.2857%", minHeight: 92, borderRightWidth: 1, borderBottomWidth: 1, padding: spacing.xs, gap: 4 },
  calendarDayNumber: { fontSize: 12, fontWeight: "900" },
  calendarTaskPill: { minHeight: 20, borderRadius: 5, justifyContent: "center", paddingHorizontal: spacing.xs },
  calendarTaskText: { color: colors.white, fontSize: 10, fontWeight: "900" },
  taskBar: {
    position: "absolute",
    top: 12,
    height: 30,
    borderRadius: 5,
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
  },
  taskBarText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "900",
  },
  todayMarker: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 2,
  },
  emptyState: {
    minHeight: 180,
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.lg,
  },
  emptyText: {
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
  },
});
